const data = {
  products: [
    {
      name: "nike slim shirt",
      slug: "nike-slim-shirt",
      category: "shirts",
      image: "/images/p1.jpg",
      price: 120,
      countinstock: 10,
      brand: "nike",
      rating: "4.5",
      numreviews: 10,
      description: "high quality shirt",
    },
    {
      name: "adidas slim shirt",
      slug: "adidas-slim-shirt",
      category: "shirts",
      image: "/images/p2.jpg",
      price: 120,
      countinstock: 10,
      brand: "adidas",
      rating: "4.5",
      numreviews: 10,
      description: "high quality shirt",
    },
    {
      name: "nike slim pant",
      slug: "nike-slim-pant",
      category: "shirts",
      image: "/images/p3.jpg",
      price: 120,
      countinstock: 10,
      brand: "nike",
      rating: "4.5",
      numreviews: 10,
      description: "high quality shirt",
    },
    {
      name: "adidas fit pant",
      slug: "adidas-fit-pant",
      category: "shirts",
      image: "/images/p4.jpg",
      price: 120,
      countinstock: 10,
      brand: "adidas",
      rating: "4.5",
      numreviews: 10,
      description: "high quality shirt",
    },
  ],
};
export default data;
